### ISSUE TITLE
I don't think I ever gave you permission to relicense all of it to ARR.

### ISSUE THREAD

**Issue by screret** [AllTheMods/gregitas-core#18]
it's not all my code, and even if it were, I wouldn't have given permission to relicense it from LGPLv3.0
could've at least asked youknow?

**Comment by screret** [comment]
...Did I ever add the license file? if not, sorry.

**Comment by screret** [comment]
it should be LGPLv3.0 *anyway*, though, as there are components that I didn't make.

**Comment by pietro-lopes** [comment]
:thinking: It is unchanged at least on CF

**Comment by thevortex** [comment]
its not ARR, its licensed as LGPLv3, check it out on curseforge. go cause drama somewhere else
